#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : epm
Version  : 3.7
Release  : 4
URL      : https://dev-www.libreoffice.org/src/3ade8cfe7e59ca8e65052644fed9fca4-epm-3.7.tar.gz
Source0  : https://dev-www.libreoffice.org/src/3ade8cfe7e59ca8e65052644fed9fca4-epm-3.7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: epm-bin
Requires: epm-license
Requires: epm-man
BuildRequires : groff
Patch1: fix-rpm-tag.patch

%description
--------------------------------------
WHAT IS EPM?
EPM is the software packaging tool that we now use at Easy
Software Products.  It is a simple tool that generates
software and patch distributions in various formats,
including:

%package bin
Summary: bin components for the epm package.
Group: Binaries
Requires: epm-license
Requires: epm-man

%description bin
bin components for the epm package.


%package doc
Summary: doc components for the epm package.
Group: Documentation
Requires: epm-man

%description doc
doc components for the epm package.


%package license
Summary: license components for the epm package.
Group: Default

%description license
license components for the epm package.


%package man
Summary: man components for the epm package.
Group: Default

%description man
man components for the epm package.


%prep
%setup -q -n epm-3.7
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535034475
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
export SOURCE_DATE_EPOCH=1535034475
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/epm
cp COPYING %{buildroot}/usr/share/doc/epm/COPYING
%make_install bindir=%{buildroot}/usr/bin mandir=%{buildroot}/usr/share/man docdir=%{buildroot}/usr/share/doc

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/epm
/usr/bin/epminstall
/usr/bin/mkepmlist

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/COPYING
/usr/share/doc/README
/usr/share/doc/epm-manual.html
/usr/share/doc/epm-manual.pdf

%files license
%defattr(-,root,root,-)
/usr/share/doc/epm/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/cat1/epm.1
/usr/share/man/cat1/epminstall.1
/usr/share/man/cat1/mkepmlist.1
/usr/share/man/cat1/setup.1
/usr/share/man/cat5/epm.list.5
/usr/share/man/cat5/setup.types.5
/usr/share/man/man1/epm.1
/usr/share/man/man1/epminstall.1
/usr/share/man/man1/mkepmlist.1
/usr/share/man/man1/setup.1
/usr/share/man/man5/epm.list.5
/usr/share/man/man5/setup.types.5
