#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v12
# autospec commit: 381dfd8
#
Name     : epm
Version  : 5.0.0
Release  : 8
URL      : https://dev-www.libreoffice.org/src/epm-5.0.0.tar.gz
Source0  : https://dev-www.libreoffice.org/src/epm-5.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: epm-bin = %{version}-%{release}
Requires: epm-license = %{version}-%{release}
Requires: epm-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : groff
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Workaround-broken-install-detection.patch

%description
ESP Package Manager (EPM)
=========================
What is EPM?
------------
EPM is a simple cross-platform tool that generates software and patch
distributions in various formats from a list of files.  Supported formats
include:

%package bin
Summary: bin components for the epm package.
Group: Binaries
Requires: epm-license = %{version}-%{release}

%description bin
bin components for the epm package.


%package doc
Summary: doc components for the epm package.
Group: Documentation
Requires: epm-man = %{version}-%{release}

%description doc
doc components for the epm package.


%package license
Summary: license components for the epm package.
Group: Default

%description license
license components for the epm package.


%package man
Summary: man components for the epm package.
Group: Default

%description man
man components for the epm package.


%prep
%setup -q -n epm-5.0.0
cd %{_builddir}/epm-5.0.0
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719440068
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719440068
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/epm
cp %{_builddir}/epm-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/epm/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
export GOAMD64=v2
GOAMD64=v2
%make_install bindir=/usr/bin mandir=/usr/share/man docdir=/usr/share/doc

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/epm
/usr/bin/epminstall
/usr/bin/mkepmlist

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/epm-book.epub
/usr/share/doc/epm-book.html
/usr/share/doc/epm-book.pdf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/epm/7df059597099bb7dcf25d2a9aedfaf4465f72d8d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/epm.1
/usr/share/man/man1/epminstall.1
/usr/share/man/man1/setup.1
/usr/share/man/man5/epm.list.5
/usr/share/man/man5/setup.types.5
